import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | KYFS Finance',
  description: 'Read the Terms of Service for KYFS Finance calculators and tools.',
}

export default function TermsOfServicePage() {
  const lastUpdated = 'April 6, 2026'
  return (
    <div className="min-h-screen py-12 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="glass-card p-8 md:p-12 space-y-8">
          <div>
            <h1 className="text-3xl font-bold mb-2" style={{ color: 'var(--fg)' }}>Terms of Service</h1>
            <p className="text-sm" style={{ color: 'var(--fg-subtle)' }}>Last updated: {lastUpdated}</p>
          </div>

          <div className="h-px" style={{ background: 'var(--card-border)' }} />

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>1. Acceptance of Terms</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              By accessing or using KYFS Finance (&quot;the Service&quot;) at kyfs.com, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service. These terms apply to all visitors, users, and others who access or use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>2. Description of Service</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              KYFS Finance provides a suite of online financial calculators (SIP, EMI, PPF, FD, and others) and tools for <strong>educational and informational purposes only</strong>. The calculations and projections provided are estimates based on inputs you supply.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>3. No Financial Advice</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              The content, calculations, and information provided by KYFS Finance do <strong>not constitute financial, investment, legal, or tax advice</strong>. The results generated by our calculators are illustrative projections and should not be the sole basis for any financial decision. Actual returns, interest rates, tax implications, and other financial outcomes may vary significantly.
            </p>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              We strongly recommend consulting with a SEBI-registered investment advisor, Certified Financial Planner (CFP), or qualified financial professional before making any financial decisions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>4. User Accounts</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              When you create an account, you must provide accurate, complete, and current information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to immediately notify us of any unauthorized use of your account.
            </p>
            <ul className="text-sm leading-relaxed space-y-1 list-disc list-inside" style={{ color: 'var(--fg-muted)' }}>
              <li>You must be at least 18 years of age to create an account.</li>
              <li>One person may not maintain more than one account.</li>
              <li>You are responsible for keeping your password secure.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>5. Acceptable Use</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              You agree not to:
            </p>
            <ul className="text-sm leading-relaxed space-y-1 list-disc list-inside" style={{ color: 'var(--fg-muted)' }}>
              <li>Use the Service for any unlawful purpose or in violation of any applicable law or regulation.</li>
              <li>Attempt to gain unauthorized access to any part of the Service, its servers, or databases.</li>
              <li>Transmit any spam, malware, viruses, or any other code that may damage the Service.</li>
              <li>Scrape, crawl, or systematically extract data from the Service without prior written permission.</li>
              <li>Use automated tools or bots to access the Service in a way that places an unreasonable load on our servers.</li>
              <li>Impersonate another person or entity.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>6. Intellectual Property</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              The Service and its original content, features, and functionality are and will remain the exclusive property of K Y Financial Services and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of K Y Financial Services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>7. Disclaimer of Warranties</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis, without any warranties of any kind, either express or implied. We do not warrant that: (a) the Service will be uninterrupted or error-free; (b) the results obtained from using the Service will be accurate or reliable; (c) any errors in the Service will be corrected.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>8. Limitation of Liability</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              To the maximum extent permitted by applicable law, K Y Financial Services shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses resulting from: (a) your use or inability to use the Service; (b) any financial decisions made based on calculator outputs; (c) any unauthorized access to your account or data.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>9. Privacy</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              Your use of the Service is also governed by our{' '}
              <Link href="/cookies-policy" className="font-semibold underline" style={{ color: 'var(--accent)' }}>Cookie Policy</Link>,
              which is incorporated into these Terms by reference. We are committed to protecting your privacy and handling your data responsibly.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>10. Modifications to Terms</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              We reserve the right to modify these Terms at any time. We will notify users of material changes by updating the &quot;Last updated&quot; date at the top of this page. Your continued use of the Service after changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>11. Governing Law</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts of Mumbai, Maharashtra, India.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold" style={{ color: 'var(--fg)' }}>12. Contact Us</h2>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--fg-muted)' }}>
              If you have any questions about these Terms of Service, please contact us at:
            </p>
            <div className="p-4 rounded-xl text-sm space-y-1" style={{ background: 'var(--input-bg)', color: 'var(--fg-muted)', border: '1px solid var(--card-border)' }}>
              <p><strong style={{ color: 'var(--fg)' }}>K Y Financial Services</strong></p>
              <p>Email: <a href="mailto:support@kyfs.com" className="underline" style={{ color: 'var(--accent)' }}>support@kyfs.com</a></p>
              <p>Phone: +91 98765 43210</p>
            </div>
          </section>

          <div className="h-px" style={{ background: 'var(--card-border)' }} />

          <p className="text-xs text-center" style={{ color: 'var(--fg-subtle)' }}>
            <Link href="/" style={{ color: 'var(--accent)' }}>← Back to Home</Link>
            {' · '}
            <Link href="/cookies-policy" style={{ color: 'var(--accent)' }}>Cookie Policy</Link>
          </p>
        </div>
      </div>
    </div>
  )
}
